# Generated by Django 2.2 on 2020-12-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0002_wall_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall_message',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_messages', to='the_wall_app.User'),
        ),
    ]
